// 389. Find the Difference

// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.

// Example:
// Input:
// s = "abcd"
// t = "abcde"
// Output:
// e
// Explanation:
// 'e' is the letter that was added.

package leetcode

func findTheDifference(s, t string) byte {
	var letter byte
	for i := 0; i < len(s); i++ {
		letter ^= s[i]
	}
	for i := 0; i < len(t); i++ {
		letter ^= t[i]
	}
	return letter
}
